// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var eventsTemplate, main, newsTemplate, reviewsTemplate, setActive, unsetActive;
    unsetActive = function() {
      return $('#header-navlinks').children().removeClass('active');
    };
    setActive = function(lnk) {
      lnk = $(lnk);
      unsetActive();
      return lnk.parent().addClass('active');
    };
    eventsTemplate = Handlebars.compile($("#events-template").html());
    newsTemplate = Handlebars.compile($("#news-template").html());
    reviewsTemplate = Handlebars.compile($("#reviews-template").html());
    main = $('#main');
    main.html(eventsTemplate);
    $('#header-navlinks').on('click', '#events-link', function(e) {
      e.preventDefault();
      setActive(this);
      return main.html(eventsTemplate());
    });
    $('#header-navlinks').on('click', '#news-link', function(e) {
      e.preventDefault();
      setActive(this);
      return main.html(newsTemplate());
    });
    return $('#header-navlinks').on('click', '#reviews-link', function(e) {
      e.preventDefault();
      setActive(this);
      return main.html(reviewsTemplate());
    });
  });

}).call(this);

//# sourceMappingURL=main.map
